CREATE TABLE categories (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO categories (name) VALUES ('Mandala');
INSERT INTO categories (name) VALUES ('Mandala Sol');